# Generated by Django 4.2.3 on 2023-07-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=100)),
                ('banco', models.CharField(choices=[('NUBANK', 'NUBANK'), ('BANCO DO BRASIL', 'BANCO DO BRASIL'), ('ITAU', 'ITAU'), ('CAIXA', 'CAIXA'), ('SANTANDER', 'SANTANDER'), ('BRADESCO', 'BRADESCO')], max_length=100)),
                ('tipo', models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('icone', models.ImageField(blank=True, null=True, upload_to='contas/imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('essencial', models.BooleanField(default=False)),
                ('valor_planejado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
