# Generated by Django 4.2.3 on 2023-07-04 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_conta_icone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contas',
            new_name='Categoria',
        ),
    ]
