# Generated by Django 4.2.3 on 2023-07-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_rename_icones_conta_icone_conta_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='valor_planejado',
            field=models.FloatField(),
        ),
    ]
