# Generated by Django 4.2.5 on 2023-11-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_categorias_valor_planejado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('NU', 'Nubank'), ('CE', 'Caixa econômica'), ('ST', 'Santander'), ('BB', 'Banco do Brasil')], max_length=2),
        ),
    ]
